// The reason is that the equality check == and comparision > < >= <= works differently.
//  Comparison converts null to a number, treating it as 0.
// That's why null >=0 is true.
// null > 0 is false.

console.log('2' > 1) // true
console.log('2' < 1) // false
console.log('2' == 1) // false
console.log('2' === 1) // false
console.log('2' != 1) // true
console.log('2' !== 1) // true
console.log('02' > 1) // false

console.log(null > 0) // false
console.log(null >= 0) // true
console.log(null < 0) // false
console.log(null <= 0) // true
console.log(null == 0) // false
console.log(null === 0) // false
console.log(null != 0) // true
console.log(null !== 0) // true
console.log(null == undefined) // true
console.log(null === undefined) // false
console.log(null != undefined) // false
console.log(null !== undefined) // true
console.log(null == null) // true
console.log(null === null) // true
console.log(null != null) // false
console.log(null !== null) // false
console.log(undefined == 0) // false
console.log(undefined === 0) // false
console.log(undefined != 0) // true
console.log(undefined !== 0) // true
console.log(undefined == undefined) // true
console.log(undefined === undefined) // true
console.log(undefined != undefined) // false
console.log(undefined !== undefined) // false
console.log(undefined == null) // true
console.log(undefined === null) // false
console.log(undefined != null) // false
console.log(undefined !== null) // true
console.log(undefined == false) // false
console.log(undefined === false) // false
console.log(undefined != false) // true
console.log(undefined !== false) // true
console.log(undefined == true) // false
console.log(undefined === true) // false
console.log(undefined != true) // true
console.log(undefined !== true) // true
console.log(undefined == '') // false
console.log(undefined === '') // false
console.log(undefined != '') // true
console.log(undefined !== '') // true
console.log(undefined == 'undefined') // false
console.log(undefined === 'undefined') // false
console.log(undefined != 'undefined') // true
console.log(undefined !== 'undefined') // true
console.log(undefined == 'null') // false
console.log(undefined === 'null') // false
console.log(undefined != 'null') // true
console.log(undefined !== 'null') // true
console.log(undefined == 'false') // false
console.log(undefined === 'false') // false
console.log(undefined != 'false') // true
console.log(undefined !== 'false') // true
console.log(undefined == 'true') // false
console.log(undefined === 'true') // false
console.log(undefined != 'true') // true
console.log(undefined !== 'true') // true
console.log(undefined == '0') // false
console.log(undefined === '0') // false
console.log(undefined != '0') // true
console.log(undefined !== '0') // true
console.log(undefined == '1') // false
console.log(undefined === '1') // false
console.log(undefined != '1') // true
console.log(undefined !== '1') // true
console.log(undefined == 'undefined') // false
console.log(undefined === 'undefined') // false
console.log(undefined != 'undefined') // true
console.log(undefined !== 'undefined') // true
console.log(undefined == 'null') // false
console.log(undefined === 'null') // false
console.log(undefined != 'null') // true
console.log(undefined !== 'null') // true
console.log(undefined == 'false') // false
console.log(undefined === 'false') // false
console.log(undefined != 'false') // true
console.log(undefined !== 'false') // true
console.log(undefined == 'true') // false
console.log(undefined === 'true') // false
console.log(undefined != 'true') // true
console.log(undefined !== 'true') // true
console.log(undefined == '0') // false
console.log(undefined === '0') // false
console.log(undefined != '0') // true
console.log(undefined !== '0') // true
